public enum SFXClips
{
	BoosterCreationSound = 0,
	GrassSound = 1,
	BushSound = 2,
	MatchSound = 3,
	MergeRotatingSound = 4,
	MissileExplosionSound = 5,
	MissileFlyingSound = 6,
	ProgressBarIncreaseSound = 7,
	Rocket = 8,
	SpawnSound = 9,
	SwapForward = 10,
	SwapBackWardSound = 11,
	TNTSound = 12,
	UIButtonSound = 13,
	LightBallPoweringEffect = 14,
	RaySound = 15,
	MatchItemExplodeSound = 16,
	LevelLoseSound = 17,
	LevelWinSound = 18,
}